plugins:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - "spec/internal/**/*"
    - "vendor/**/*"
    - "gemfiles/**/*"
    - "lib/devise/strategies/database_authenticatable.rb"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Rspec/NestedGroups:
  Max: 4
